apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
      - name: listener
        image: me-west1-docker.pkg.dev/dgt-gcp-moe-devops/bbg-gke-test/listener:1.0.4
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: dev
        # - name: RABBITMQ_HOST --> check
        #   value: rabbitmq.default.svc.cluster.local # <service-name>.<namespace>.svc.cluster.local
        # - name: RABBITMQ_PORT
        #   value: "5672"
        # - name: RABBITMQ_USER
        #   value: "myuser"
        # - name: RABBITMQ_PASSWORD
        #   value: "mypassword"
        # - name: REDIS_HOST
        #   value: redis-service.default.svc.cluster.local # <service-name>.<namespace>.svc.cluster.local
        # - name: REDIS_PORT
        #   value: "6379"
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.dev.json
          subPath: appsettings.dev.json
      volumes:
      - name: config-volume
        configMap:
          name: listener-appsettings-config