apiVersion: batch/v1
kind: CronJob
metadata:
  name: publisher-cronjob
spec:
  schedule: "*/1 * * * *"  # Run every 1 minutes (TEST)
  # schedule: "0 * * * *"  # Run every hour
  jobTemplate:
    spec:
      parallelism: 4 # Run 4 pods simultaneously
      ttlSecondsAfterFinished: 120
      template:
        spec:
          containers:
          - name: publisher
            image: [IMAGE LOCATION] # Replace HERE
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "256Mi"
                cpu: "500m"
            env:
            - name: ASPNETCORE_ENVIRONMENT
              value: dev
            volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.dev.json
              subPath: appsettings.dev.json
          volumes:
          - name: config-volume
            configMap:
              name: publisher-appsettings-config
          restartPolicy: Never  # Ensures the job doesn't restart if it fails
      activeDeadlineSeconds: 3300  # Ensure the job runs for only 2 minutes
  successfulJobsHistoryLimit: 1  # Keep history of the last successful job
  failedJobsHistoryLimit: 1       # Keep history of the last failed job
