apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
  type: ClusterIP
