apiVersion: v1
kind: ConfigMap
metadata:
  name: listener-appsettings-config
  namespace: {{ .Values.namespace }}
data:
  appsettings.dev.json: |
{{ .Files.Get "files/appsettings/listen-conf/appsettings.dev.json" | indent 4 }}
